create modale-order markup and add css styles
MaksymBora/Palate-Paradise pull request #6
Opened 2023-07-22 11:07 UTC by galu4ok

2023-07-22 15:09 UTC, MaksymBora requested changes
перероби трохи форму ось так
<label class="modal-order-form__field">
  <span for="user-tel" class="modal-order-form__label">Phone number</span>
  <input
    type="tel"
    name="user-name"
    id="user-tel"
    class="modal-order-form__input"
    required
    pattern="^ [0-9] + $"
    title="Please enter the phone in the number format"
  />
</label>

2023-07-23 10:31 UTC, galu4ok commented
Розмітку не змінювала, оскільки 5 px згубилися на скролі.Розміри модалки звірила з макетом, все ок

2023-07-23 21:09 UTC, MaksymBora reviewed
Написав в телеграмі

2023-07-24 20:33 UTC, galu4ok commented
done

2023-07-25 01:45 UTC, MaksymBora approved these changes

2023-07-25 01:45 UTC, merged